apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::724935662937:role/UdacityFlaskDeployCBKubectlRole
           username: build
           groups:
             - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::724935662937:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8XKDBZS5U5PO
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-20T15:30:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5483"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fb131b67-b822-4c66-9f93-58681d90686d
