apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<account_id>:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<account_id>:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GSLBPYWGBZNP
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-24T16:05:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12370"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: be09859b-982a-40ed-f6f8-9ff3fc09a0a3
